// PRODUCTS
export const GET_PRODUCTS_PROCESS = "GET_PRODUCTS_PROCESS";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_ERROR = "GET_PRODUCTS_ERROR";
export const GET_BOOKS_SUCCESS = "GET_BOOKS_SUCCESS";
export const GET_ELECTRONICS_SUCCESS = "GET_ELECTRONICS_SUCCESS";
export const GET_OUTDOOR_SUCCESS = "GET_OUTDOOR_SUCCESS";
export const GET_GARDEN_SUCCESS = "GET_GARDEN_SUCCESS";
